#!/bin/bash

LOG=""
#LOG="1"

MONITOR=""
#MONITOR="--monitor"

PORT="--port=`shuf -i 2000-65000 -n 1`"
SYNC="--synch-mode"

if [ ! -z $LOG ]; then
    LOG="--log-dir=logs --log-game --log-text --log-level 101"
fi

if [ ! -z $MONITOR ]; then
    SYNC=""
fi

ulimit -c unlimited
./build.sh

